---
# Commands to run before building
before_script:
  # Install cabal, the package manager for programs like pandoc that are
  # written in the Haskell language.
  - sudo apt-get install cabal-install
  # Install the zip archiver.
  - sudo apt-get install zip
  # Update cabal's list of available packages.
  - cabal update
  # Install pandoc
  - cabal install pandoc
  # Add the directory where pandoc will be installed to the list of
  # directories the operating system will search.
  - export PATH=$HOME/.cabal/bin:$PATH

# Upload SeriesSeed.zip as a GitHub release for every tagged commit.
deploy:
  provider: releases
  api_key:
    secure: OboOkvnsBsGZFXg4ZjUdQqgLahn3it/Pj1jWoTbeEYy26AhAt/iljTRfmJt1LJ2RtzqlNxt6+m1M/wVthExKUnBCWu6gX+XqYt3MiZPl5SjwKNuo5kAM43/XPEMsGVL15CIHH9JKQ4Awo05OH9jGv1DVVeGGg3WH2vEVuKYfqzw=
  file: SeriesSeed.zip
  skip_cleanup: true
  on:
    repo: kemitchell/equity
    tags: true

# Use rake to build SeriesSeed.zip
language: ruby
script: rake
