---
before_script:
  - sudo apt-get update
  - sudo apt-get install -y pandoc zip

deploy:
  provider: releases
  api_key:
    secure: OboOkvnsBsGZFXg4ZjUdQqgLahn3it/Pj1jWoTbeEYy26AhAt/iljTRfmJt1LJ2RtzqlNxt6+m1M/wVthExKUnBCWu6gX+XqYt3MiZPl5SjwKNuo5kAM43/XPEMsGVL15CIHH9JKQ4Awo05OH9jGv1DVVeGGg3WH2vEVuKYfqzw=
  file: SeriesSeed.zip
  skip_cleanup: true
  on:
    repo: kemitchell/equity
    tags: true

language: ruby
script: bundle exec rake
